### ISSUE TITLE
Provide simple example

### ISSUE THREAD

**Issue by exap** [cbeck88/spirit-po#3] opened 2017-06-10 13:52 UTC
It would be nice if there would be a simple example to get started.

**Comment by cbeck88** [comment] 2017-06-10 19:10
This is a good point, I will think on how to improve the documentation in this way.

**Comment by cbeck88** [comment] 2017-07-27 16:49
So, I'm still not sure what's the best way to make a simple example, and especially, who should the target audience be.

The problem is that, gettext is not really that simple. gettext is good because a lot of thought and care has been put it into it so that programmer workflows don't interfere with translator workflows to the extent possible, and a lot of steps in the translation process can be nicely automated. It's not easy to get explain to a newbie what all that means quickly, so if I just start showing example code, there's going to be a lot of things that, they won't really understand why they are there.

If you aren't already somewhat familiar with it, I'm not sure if there's a good way to get into it, other than to the gettext docs or look at large programs that use it in detail. My fear is that a minimal "example, fully-gettextized program" is actually going to be too complex and have too much boiler-plate to be helpful. And I don't really want to write a "minimal intro to gettext", just to get people to the point where they can understand what this library does and how it fits in precisely, because that's basically doing them a disservice -- it will contain very little useful information. I'm worried that I kind of already did that on the wiki, and it's just a wall of text.

If someone is *already* familiar with gettext, then they will probably have a pretty good idea how to get started, and they won't really need a simple example. They need to go figure out where they are using `libintl` and replace that with `spirit_po` if that's what they want to do. 

I can do things like, point to projects like [Wesnoth](https://github.com/wesnoth/wesnoth) that merged PR's like that. So that people can look at how a patch like that might look.

It may also be that I need to go find a really good intro to gettext that someone else wrote and link to it, or link to a series of pages within the official docs or something.

If you can help me understand what kind of examples would be helpful, what things aren't clear, or what you might have had in mind, that would be great. Thanks!

**Comment by cbeck88** [comment] 2017-08-07 05:31
I added a little quickstart to the README, I think it's an improvement. Thanks for this suggestion.

**Comment by exap** [comment] 2017-08-09 22:14
Thank you for the example :)

**Closed as completed** 2017-08-09 22:15 UTC
